services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "nginx:80"
    ports:
      - "4040:4040"
    networks:
      - cchistory-network
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    depends_on:
      - nginx
    restart: unless-stopped