services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cchistory-backend
    environment:
      - CLAUDE_PROJECTS_PATH=/data/projects
      - CLAUDE_PROJECTS=${CLAUDE_PROJECTS:-}
      - TIMEZONE=${TIMEZONE:-Asia/Tokyo}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ${CLAUDE_PROJECTS_PATH:-/Users/masanao.oba/.claude/projects}:/data/projects:ro
    ports:
      - "${VIEWER_PORT:-18080}:8000"
    networks:
      - cchistory-network
    restart: unless-stopped

networks:
  cchistory-network:
    driver: bridge