services:
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "--oauth"
      - "google"
      - "--oauth-allow-email"
      - "${NGROK_OAUTH_ALLOW_EMAIL:-}"
      - "--oauth-allow-domain"
      - "${NGROK_OAUTH_ALLOW_DOMAIN:-}"
      - "nginx:80"
    ports:
      - "4040:4040"
    networks:
      - cchistory-network
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_DOMAIN=${NGROK_DOMAIN}
    depends_on:
      - nginx
    restart: unless-stopped